a = str("KBTU")
b = int(20)
c = float(20.5)
d = complex(1j)
e = list(("Astana", "Almaty"))
f = tuple(("Astana", "Almaty"))
g = range(6)
h = dict(name = "Alex", age = 19)
i = set(("Astana", "Almaty"))
j = frozenset(("Astana", "Almaty"))
k = bool(5)
l = bytes(5) 
m = bytearray(5)
n = memoryview(bytes(5))

print(a, b, c, d, e, f, g, h, i, j, k, l, m, n)